language: python

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=docs
    - TOX_ENV=pep8

matrix:
    allow_failures:
        - python: "2.7"
          env: TOX_ENV=pep8

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
